- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/Petstore

    - name: tag image
      command: docker tag petstore:latest ankillaraghu/petstore:latest 

    - name: Log in to Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: ankillaraghu
        password: dckr_pat_PKdRbMC5-Yg1Ux_4st3kUALC2eY
        reauthorize: yes

    - name: Push image
      command: docker push ankillaraghu/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8081 ankillaraghu/petstore:latest
